apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wgctw3iab-nodejs
  janus-idp.io/tekton: wgctw3iab-nodejs
  backstage.io/kubernetes-id: wgctw3iab-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wgctw3iab-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
