apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wgctw3iab-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wgctw3iab-nodejs 
  name: wgctw3iab-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: wgctw3iab-nodejs 
